### ISSUE TITLE
由于返回值过长（超过5kb）直接解码报错Java文件名或扩展名过长的报错

### ISSUE THREAD

**Issue by VBPush** [0xf4n9x/CDGXStreamDeserRCE#2]
程序“java.exe”无法运行: 文件名或扩展名太长。所在位置 行:1 字符: 1
+ java -jar .\CDGXStreamDeserRCE.jar -d "FEPCCCLCENHIPOAFPAPDDFCGEAPNMD ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~。
所在位置 行:1 字符: 1
+ java -jar .\CDGXStreamDeserRCE.jar -d "FEPCCCLCENHIPOAFPAPDDFCGEAPNMD ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

4W多个字符

**Comment by 0xf4n9x** [comment]
这个问题可能是由于某些终端软件对接收的命令做出了限制长度，超过一定长度就无法正常执行命令。

在macOS上使用iTerm2运行如此长度的命令倒是能正常工作的。

```bash
java -jar CDGXStreamDeserRCE.jar -d FEPCCCLCENHIPOAFPA.....
[+] Decode Successed:
<?xml version='1.0' encoding="gb2312"?>
<CDGAuthoriseTemplet>
  <authoriseTempletList>
    <AuthoriseTemplet>
      <name>SystemAdmin</name>
      <description>3FF8A0978
....
```

也是超过4万的长度。
```bash
history | grep 'LBNMFNNJNIIFPFNALJLLKDCJLLIDFBGHKGNFEBHLHIDGLEGPFMFGGGCJ' | awk '{print length($0)}'
44277
```

**Comment by VBPush** [comment]
> 这个问题可能是由于某些终端软件对接收的命令做了限制长度，超过一定长度就无法正常执行命令。
> 
> 在macOS上使用iTerm2运行如此长度的命令倒是能正常工作的。
> 
> ```shell
> java -jar CDGXStreamDeserRCE.jar -d FEPCCCLCENHIPOAFPA.....
> [+] Decode Successed:
> <?xml version='1.0' encoding="gb2312"?>
> <CDGAuthoriseTemplet>
>   <authoriseTempletList>
>     <AuthoriseTemplet>
>       <name>SystemAdmin</name>
>       <description>3FF8A0978
> ....
> ```
> 
> 也是超过4万年的历史。
> 
> ```shell
> history | grep 'LBNMFNNJNIIFPFNALJLLKDCJLLIDFBGHKGNFEBHLHIDGLEGPFMFGGGCJ' | awk '{print length($0)}'
> 44277
> ```
可以让jar支持-d的解码以文件方式读取吗

**Comment by 0xf4n9x** [comment]
已更新，见https://github.com/0xf4n9x/CDGXStreamDeserRCE/releases/tag/v1.3.3
